### ISSUE TITLE
connection with ibm failed, if you can explain how to connect step by step please, it will be very helpful, thank you

### ISSUE THREAD

**Issue by mehdibil** [unclevito2017/Quantum-mining-puzzle-66#2]
python quantum-run-simulator.py/home/mehdi/Downloads/Quantum-mining-puzzle-66-main/quantum-run-simulator.py:28: DeprecationWarning: The package qiskit.providers.ibmq is being deprecated. Please see https://ibm.biz/provider_migration_guide to get instructions on how to migrate to qiskit-ibm-provider (https://github.com/Qiskit/qiskit-ibm-provider) and qiskit-ibm-runtime (https://github.com/Qiskit/qiskit-ibm-runtime).
  IBMQ.load_account()
/home/mehdi/Downloads/Quantum-mining-puzzle-66-main/quantum-run-simulator.py:28: DeprecationWarning: The qiskit.IBMQ entrypoint and the qiskit-ibmq-provider package (accessible from 'qiskit.providers.ibmq`) are deprecated and will be removed in a future release. Instead you should use the qiskit-ibm-provider package which is accessible from 'qiskit_ibm_provider'. You can install it with 'pip install qiskit_ibm_provider'. Just replace 'qiskit.IBMQ' with 'qiskit_ibm_provider.IBMProvider'
  IBMQ.load_account()
Traceback (most recent call last):
  File "/home/mehdi/Downloads/Quantum-mining-puzzle-66-main/quantum-run-simulator.py", line 82, in <module>
    main()
  File "/home/mehdi/Downloads/Quantum-mining-puzzle-66-main/quantum-run-simulator.py", line 28, in main
    IBMQ.load_account()
  File "/home/mehdi/.local/lib/python3.11/site-packages/qiskit/providers/ibmq/ibmqfactory.py", line 167, in load_account
    raise IBMQAccountCredentialsNotFound(
qiskit.providers.ibmq.exceptions.IBMQAccountCredentialsNotFound: 'No IBM Quantum Experience credentials found.'

**Comment by unclevito2017** [comment]
looks like you either have not signed up for an account https://quantum.ibm.com/ or you have not went into the account you signed up for and copied your assigned API  into quantum_login-step1.py open file in notepad and paste your API into  'YOUR_API_TOKEN' between the quotes the API token is in your account   
![account](https://github.com/unclevito2017/Quantum-mining-puzzle-66/assets/37158637/3d1a57f4-d27e-4f7a-818d-623876a83195)

**Comment by mehdibil** [comment]
thank you for assistance, i have run it but after generation 1003 jobs it taked more then 2 hours it give me this result : 


ibmqfactory.load_account:WARNING:2023-12-14 17:45:11,335: Credentials are already in use. The existing account in the session will be replaced.
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
       ^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
       ^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 889, in urlopen
    **response_kw,
       ^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 879, in urlopen
    retries,
             
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/api/session.py", line 104, in increment
    return super().increment(
           ^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/backends/ibmq_qasm_simulator/configuration (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/api/session.py", line 263, in request
    response = super().request(method, final_url, headers=headers, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/backends/ibmq_qasm_simulator/configuration (Caused by ResponseError('too many 500 error responses'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_4959/2447092738.py", line 82, in <module>
    main()
  File "/tmp/ipykernel_4959/2447092738.py", line 62, in main
    backend = provider.get_backend('ibmq_qasm_simulator')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/ibm_provider.py", line 660, in get_backend
    backends = self.backends(name, instance=instance, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/ibm_provider.py", line 561, in backends
    return self._backend.backends(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/ibm_backend_service.py", line 168, in backends
    self._set_backend_config(name)
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/ibm_backend_service.py", line 674, in _set_backend_config
    raw_config = self._provider._runtime_client.backend_configuration(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/api/clients/runtime.py", line 101, in backend_configuration
    return self._api.backend(backend).configuration()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/api/rest/backend.py", line 122, in configuration
    return self.session.get(url).json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/qiskit_ibm_provider/api/session.py", line 285, in request
    raise RequestsApiError(message, status_code) from ex
qiskit_ibm_provider.api.exceptions.RequestsApiError: "HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/backends/ibmq_qasm_simulator/configuration (Caused by ResponseError('too many 500 error responses'))"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2120, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1435, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1326, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1192, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1088, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 970, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
    ^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py", line 792, in lines
    return self._sd.lines
           ^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
                                               ^^^^^^^^^^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
           ^^^^^
  File "/home/quantum/anaconda3/lib/python3.11/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0

**Comment by unclevito2017** [comment]
according to the first line you were trying to rum the program that you already had running   "Credentials are already in use. The existing account in the session will be replaced."

**Comment by mehdibil** [comment]
the first line was already existed from the begging , but the rest was mentioned after the jobs bulding..what is it mean ?

**Comment by unclevito2017** [comment]
try running python3 quantum-check-if-connected.py if it says you are connected to the API then only run quantum-run-simulator.py don't keep running quantum_login-step1. The rest is  a error saying he program tried to connect the maximum times but could not because it is already connected.

**Comment by unclevito2017** [comment]
when you first run the simulator or go live you should se
quantum-run-simulator.py:28: DeprecationWarning: The package qiskit.providers.ibmq is being deprecated. Please see https://ibm.biz/provider_migration_guide to get instructions on how to migrate to qiskit-ibm-provider (https://github.com/Qiskit/qiskit-ibm-provider) and qiskit-ibm-runtime (https://github.com/Qiskit/qiskit-ibm-runtime).
  IBMQ.load_account()
quantum-run-simulator.py:28: DeprecationWarning: The qiskit.IBMQ entrypoint and the qiskit-ibmq-provider package (accessible from 'qiskit.providers.ibmq`) are deprecated and will be removed in a future release. Instead you should use the qiskit-ibm-provider package which is accessible from 'qiskit_ibm_provider'. You can install it with 'pip install qiskit_ibm_provider'. Just replace 'qiskit.IBMQ' with 'qiskit_ibm_provider.IBMProvider'
  IBMQ.load_account()
then you will see nothing until either 1. you find the solution  2. you run out of your 10 minutes on a live node  3 the message no solution found. On your dashboard you will see the count     if you are on the simulator too long and the system is busy it may disconnect you to allow others to use it. Remember the simulator is just checking if the software works
